In [1]:
import os
import torch
from PIL import Image
import torchvision
import torchvision.transforms as transforms
from torch.autograd import Variable
import torch.nn.functional as F
from net import AGNet
from PIL import ImageFont, ImageDraw


In [2]:
net = AGNet()

In [3]:
state = torch.load("checkpoint/ckpt.pth", map_location='cpu')

In [38]:
net.load_state_dict(state['net'])

In [60]:
state[]

{'net': OrderedDict([('backbone.conv1.weight',
               tensor([[[[ 0.0328, -0.0718, -0.0378,  ...,  0.0310, -0.0117, -0.0453],
                         [ 0.0770, -0.0435, -0.0110,  ..., -0.0390,  0.0326,  0.0138],
                         [ 0.0135,  0.0100, -0.0208,  ..., -0.0219, -0.0882,  0.0080],
                         ...,
                         [ 0.0546,  0.0234,  0.0643,  ...,  0.0581, -0.0486, -0.0561],
                         [-0.0105,  0.0793, -0.0427,  ..., -0.0298,  0.0297,  0.0155],
                         [ 0.0568,  0.0634,  0.0648,  ...,  0.0222,  0.0407,  0.0778]],
               
                        [[ 0.0274,  0.0319, -0.0098,  ..., -0.0750,  0.0435, -0.0511],
                         [-0.0395, -0.0403,  0.0047,  ..., -0.0654, -0.0832,  0.0522],
                         [-0.0509,  0.0088,  0.0809,  ...,  0.0646,  0.0138, -0.0456],
                         ...,
                         [-0.0451, -0.0410,  0.0183,  ...,  0.0806,  0.0633,  0.0726],
      

In [40]:
transform_image = transforms.Compose([
    transforms.CenterCrop(150),
    transforms.ToTensor(),
    transforms.Normalize((0.485,0.456,0.406), (0.229,0.224,0.225))
])

In [41]:
path = "/home/damvantai/Documents/projects/predict_age_gender/data/test_2/"
font = ImageFont.truetype("/home/damvantai/Downloads/Aaargh.ttf", 16)

for filename in os.listdir(path):
    img = Image.open(path + filename)
    draw = ImageDraw.Draw(img)
    input_img = transform_image(img)
    input_img.unsqueeze_(0).shape
    age, gender = net(Variable(input_img))
    gender_preds = F.sigmoid(gender)
    print(gender_preds)
    gender_preds = (gender_preds > 0.5).int()
    if gender_preds == 0:
        label = "male"
    if gender_preds == 1:
        label = "female"
    print(label)  
    draw.text((0, 0), label, (255,0,255), font=font)
    img.save(filename)

/home/damvantai/.local/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([0.4258], grad_fn=<SigmoidBackward>)
male
tensor([0.3971], grad_fn=<SigmoidBackward>)
male
tensor([0.3919], grad_fn=<SigmoidBackward>)
male
tensor([0.4011], grad_fn=<SigmoidBackward>)
male
tensor([0.4012], grad_fn=<SigmoidBackward>)
male
tensor([0.3884], grad_fn=<SigmoidBackward>)
male
tensor([0.4016], grad_fn=<SigmoidBackward>)
male
tensor([0.3337], grad_fn=<SigmoidBackward>)
male
tensor([0.4012], grad_fn=<SigmoidBackward>)
male
tensor([0.4060], grad_fn=<SigmoidBackward>)
male
tensor([0.4163], grad_fn=<SigmoidBackward>)
male
tensor([0.4168], grad_fn=<SigmoidBackward>)
male
tensor([0.3490], grad_fn=<SigmoidBackward>)
male
tensor([0.3566], grad_fn=<SigmoidBackward>)
male
tensor([0.3903], grad_fn=<SigmoidBackward>)
male
tensor([0.3912], grad_fn=<SigmoidBackward>)
male
tensor([0.4107], grad_fn=<SigmoidBackward>)
male
tensor([0.4076], grad_fn=<SigmoidBackward>)
male
tensor([0.4317], grad_fn=<SigmoidBackward>)
male
tensor([0.3625], grad_fn=<SigmoidBackward>)
male
tensor([0.3643], gra

In [53]:
path = "/home/damvantai/Documents/projects/predict_age_gender/data/test_2/17_1_4_20170103201513799.jpg.chip.jpg"

In [54]:
img = Image.open(path)

In [55]:
input_img = transform_image(img)
input_img.shape

torch.Size([3, 150, 150])

In [56]:
input_img.unsqueeze_(0).shape
input_img.shape

torch.Size([1, 3, 150, 150])

In [57]:
a, b = net(input_img)

In [58]:
b

tensor([-0.3251], grad_fn=<ViewBackward>)

In [59]:

gender_preds = F.sigmoid(b)
print(gender_preds)
gender_preds = (gender_preds > 0.5).int()
if gender_preds == 0:
    label = "male"
if gender_preds == 1:
    label = "female"
print(label)  

tensor([0.4194], grad_fn=<SigmoidBackward>)
male


/home/damvantai/.local/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
